
class FetchRecordsService(object):
    def __init__(self, db_client):
        self.db_client = db_client

    def fetch_classified_records(self):
        ...
    def fetch_source_item_hashed_records(self):
        ...
    def fetch_zipped_records(self):
        ...
    def fetch_zipped_item_hashed_records(self):
        ...
    def fetch_unzipped_records(self):
        ...
    def fetch_unzipped_item_hashed_records(self):
        ...
    def fetch_upload_records(self):
        ...
    def fetch_delete_records(self):
        ...
    
