
class PersistRecordsService(object):
    def __init__(self, db_client):
        self.db_client = db_client

    def persist_classified_records(self):
        ...
    def persist_source_item_hashed_records(self):
        ...
    def persist_zipped_records(self):
        ...
    def persist_zipped_item_hashed_records(self):
        ...
    def persist_unzipped_records(self):
        ...
    def persist_unzipped_item_hashed_records(self):
        ...
    def persist_upload_records(self):
        ...
    def persist_delete_records(self):
        ...
    
